travis:
  secure:
    BINSTAR_TOKEN: m4mkR5CHw7jARHho69dCMK/afptY7inkL/V96Sv7fLfXQgFeNhvnEzFEaMd3r6YGSbbXwHZQDZt8u901YQ/lq90wEFRszq7dU3hw1+qCFY4eLe1pPIuh6N+50LizNq5KVrZTqyTU3PO+zYkPEwTAGt7gaL8lT/vMCL4Pw4JgjtM47b8kEjLxG9slvtlg+atFv3N/JXRNu98ZOPJN/28wHPzbLxP5tfH8Ui9x8sJFXOeSGDxqIEQEIrCsQHzb6IZ+JhXpzVS7jVfoaH+hO5Mmmjf4gZR0Tb7+zqA5KpKhf9wbIkOGkROXcjsEU1iWz1376mmvWe8Ob9LofjcUBp3Vn/oepGYLOQ4ckJk4OW4G7JK5EBk3+YCjmgyClEeCJW5sLADoqDcjVmbiCCk1TfBQA7dIukIKR9pP6ilMM41ZnXqkZjfUClURO4/u3wV2S32L6U0SnM60jKSYDd/T3ePK9dCuRQVymeSDnBv0Vw4RpmArpNOqISxgEKj/EQ2n0fgNB5Zex/XBzrJTCfszrm8cdcwsS/gVn7qJtStl2dJnp8zQiceGTe/sbTaskllCboBtOw0uh8+6GrQgWcqtTaHJMQTJOYWg/JoL154L51+UUyzRAK7a9H/5Z2F7OPoVXN8UtIQ6wRt1cgPXjczysR7NIWR3Kd7tAGFTsKID1u3V1mY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
